apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-qu
  namespace: production
spec:
  hard:
    cpu: "2"
    memory: 2Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: 10
    services: 5                
