apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-ns-update
  namespace: update
spec:
  hard:
    cpu: "0.2"
    memory: 50Mi
    limits.cpu: 2
    limits.memory: 1Gi
    pods: 5
    count/services: 5
    count/deployments.apps: 3
    count/replicasets.apps: 4
